# docker compose -f docker-compose-back.yml up -d

version: "3.1"

services:
  iris_db:
    container_name: iris
    image: supabase/postgres:14.1.0.21
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./conf/db:/docker-entrypoint-initdb.d
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          timeout: 5s
          retries: 5

  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm

  atlas_redis:
    container_name: atlas
    image: redis/redis-stack:latest
    restart: unless-stopped
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --save 60 1"
    volumes:
      - ./volumes/redis/data:/data
    ports:
      - ${ATLAS_PORT}:6379
    depends_on:
      - redis-overcommit

  ares_api:
    container_name: ares
    image: dune_ares:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: ../ares/app
        target: /ares/app
      - type: bind
        source: ../bacchus
        target: /bacchus
    ports:
      - ${ARES_PORT}:5100
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DD_SERVICE="Triton-L2"
      - DD_ENV="prod"
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
      - DD_APPSEC_ENABLED=true
      - DD_SITE=us5.datadoghq.com
      - DD_AGENT_HOST=65.21.91.39
    depends_on:
      iris_db:
        condition: service_healthy
      atlas_redis:
        condition: service_started

  triton_api:
    container_name: triton
    image: dune_triton:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: ../triton/app
        target: /triton/app
      - type: bind
        source: ../bacchus
        target: /bacchus
    ports:
      - ${TRITON_PORT}:5110
    environment:
      - DD_SERVICE="Triton-L1"
      - DD_ENV="prod"
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
      - DD_APPSEC_ENABLED=true
      - DD_SITE=us5.datadoghq.com
      - DD_AGENT_HOST=65.21.91.39
    depends_on:
      - iris_db
      - atlas_redis
